version: "3.8"

services:
  api:
    container_name: backend
    restart: on-failure
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: bash -c "uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: database
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d database -U admin"]
      interval: 30s
      timeout: 10s
      retries: 5

  ngrok:
    image: wernight/ngrok
    restart: always
    ports:
      - "4040:4040" # Optional: Expose ngrok web interface
    environment:
      NGROK_AUTH: 2TotUK3LZvl3UpzaqoPrUgecrgb_4WQpi1x63HkGgVPZv4oPL # Replace with your ngrok auth token
      NGROK_PORT: api:8000 # Point to your backend service
    command: ngrok http api:8000
